# docker-compose.yml
version: "3.7"
services:
  application:
    build:
      args:
        user: lachlan
        uid: 1000
      context: .
      dockerfile: ./docker/application/Dockerfile.application
    container_name: application
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    env_file: .env
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_HOST
      - MYSQL_DRIVER
      - MYSQL_HOST


  
  database:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile.postgres
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  webserver:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.nginx
    container_name: webserver
    restart: unless-stopped
    depends_on:
      - application
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
